<h5> <?php echo  "Today: " . date('Y-m-d') ?></h5>
<h5> <?php echo  "Date end: " . $block->getAnyCustomValue(); ?></h5>

<div id="getting-started"></div>

<script>
    require([
        'jquery',
        'countdown'
    ], function ($) {
        $(document).ready(function () {
                $("#getting-started")
                    .countdown("<?php echo  $block->getAnyCustomValue(); ?>", function(event) {
                        $(this).text(
                            event.strftime('%D days %H:%M:%S')
                        );
                    });
        });
    });
</script>